### PR TITLE
Add .python-version file for ST4

### PR DESCRIPTION
**Pull request by themilkman**
This will let ST >=4 builds use the 3.8 plugin host instead of the old 3.3.
I've had this running for quite a long time and it did work as expected.

Cheers & thanks for your helpful plugin!

### CODE REVIEW

**Comment by themilkman** [comment]
Any chance to get this merged and released, @bpicolo ? :-)

**Comment by bpicolo** [comment]
@themilkman Absolutely! Thank you. Glad to see some folk still find this useful.

Released...might be a harder question, will see what I can do. I don't have any recollection on how to do that haha

**Comment by bpicolo** [comment]
Well, I tagged a release on github. Reading through https://packagecontrol.io/docs/submitting_a_package, I think that's all I need? 

As far as I can tell, the metadata is still configured, and nothing jumps out as being incorrect in the modern era:
https://github.com/wbond/package_control_channel/blob/master/repository/c.json#L3766

The version is still 2014 on https://packagecontrol.io/packages/Copy%20Relative%20Path though. My current guess is it takes time for the package manager to pick up new versions. Can you confirm or deny that @themilkman ?

edit: actually, it looks like this package still uses deprecated branch-based versioning... I can probably go update that in the other repo

**Comment by bpicolo** [comment]
Created a PR in that repo to switch to tag-based versioning: https://github.com/wbond/package_control_channel/pull/8714

**Comment by themilkman** [comment]
Thank you so much @bpicolo ! 

Unfortunately I do not maintain any package on my own and do not know how the release process works... :see_no_evil:  hopefully your way succeeds. What I do know is that it sometimes takes a little bit of time until the new version appears on the pc website (I guess there is a periodic crawler).

I'll stay tuned. Again thank you very much!

**Comment by themilkman** [comment]
It arrived, thanks again for your work! :pray: :-)

**Pull request merged**
